export const profiles = [
    {
      id: 1,
      name: "Sophie Martin",
      title: "Full Stack Developer",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJ8PzPLg8d2HJkNytkC-WYHjElSVJ3fHRfw&s",
      skills: ["React", "Node.js", "TypeScript", "MongoDB"],
      description: "Passionate developer with 5 years of experience in building modern web applications.",
      location: "Paris, France",
    },
    {
      id: 2,
      name: "Thomas Dubois",
      title: "UX/UI Designer",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJ8PzPLg8d2HJkNytkC-WYHjElSVJ3fHRfw&s",
      skills: ["Figma", "Adobe XD", "Sketch", "Prototyping"],
      description: "Creative designer specializing in crafting intuitive and aesthetic user interfaces.",
      location: "Lyon, France",
    },
    {
      id: 3,
      name: "Camille Leroy",
      title: "Digital Marketing Specialist",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJ8PzPLg8d2HJkNytkC-WYHjElSVJ3fHRfw&s",
      skills: ["SEO", "Social Media", "Google Ads", "Data Analysis"],
      description: "Expert in digital marketing strategies with a strong focus on measurable results.",
      location: "Bordeaux, France",
    },
    {
      id: 4,
      name: "Alexandre Petit",
      title: "Agile Project Manager",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJ8PzPLg8d2HJkNytkC-WYHjElSVJ3fHRfw&s",
      skills: ["Scrum", "Jira", "Team Management", "Planning"],
      description: "Experienced project manager with a solid background in Agile and Scrum methodologies.",
      location: "Toulouse, France",
    },
    {
      id: 5,
      name: "Émilie Bernard",
      title: "Mobile Developer",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJ8PzPLg8d2HJkNytkC-WYHjElSVJ3fHRfw&s",
      skills: ["React Native", "Flutter", "iOS", "Android"],
      description: "Specialist in developing high-performance and elegant cross-platform mobile applications.",
      location: "Nantes, France",
    },
    {
      id: 6,
      name: "Lucas Moreau",
      title: "Cybersecurity Expert",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJ8PzPLg8d2HJkNytkC-WYHjElSVJ3fHRfw&s",
      skills: ["Pentesting", "Security Audits", "Cryptography", "DevSecOps"],
      description:
        "IT security consultant with expertise in protecting critical infrastructures.",
      location: "Lille, France",
    },
  ]

 export const profilesDetails = [
    {
      id: 1,
      name: "Sophie Martin",
      title: "Full Stack Developer",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlJ8PzPLg8d2HJkNytkC-WYHjElSVJ3fHRfw&s",
      skills: ["React", "Node.js", "TypeScript", "MongoDB"],
      description: "Passionate developer with 5 years of experience in building modern web applications.",
      longDescription:
        "I am a full stack developer with strong expertise in JavaScript and its modern frameworks. I enjoy solving complex problems and creating high-performance, scalable applications. My passion for continuous learning allows me to stay updated with the latest technologies and best practices in web development.",
      location: "Paris, France",
      email: "sophie.martin@example.com",
      phone: "+33 6 12 34 56 78",
      website: "www.sophiemartin.dev",
      available: true,
      memberSince: "January 2020",
      skillsDetails: [
        { name: "React", level: "Expert", percentage: 95 },
        { name: "Node.js", level: "Advanced", percentage: 85 },
        { name: "TypeScript", level: "Advanced", percentage: 80 },
        { name: "MongoDB", level: "Intermediate", percentage: 70 },
        { name: "GraphQL", level: "Intermediate", percentage: 65 },
        { name: "Docker", level: "Beginner", percentage: 50 },
      ],
      experience: [
        {
          position: "Senior Full Stack Developer",
          company: "TechInnovate",
          period: "2021 - Present",
          description:
            "Developed complex web applications using React, Node.js, and MongoDB. Technical lead of a team of 4 developers.",
        },
        {
          position: "Front-end Developer",
          company: "WebSolutions",
          period: "2018 - 2021",
          description: "Created responsive and accessible user interfaces with React and TypeScript.",
        },
        {
          position: "Junior Developer",
          company: "StartupVision",
          period: "2016 - 2018",
          description: "Developed front-end and back-end features for a growing SaaS platform.",
        },
      ],
    },
  ]